### PR TITLE
disable metrics from localhost 3000

### PR DESCRIPTION
**Pull request by mrosata**
Disable sending metrics to CTW from localhost:3000

### CODE REVIEW

**Review by luthfib — APPROVED** [review]

**Comment by luthfib** [comment]
It seems you have a telemetry test you need to disable

**Review by luthfib — CHANGES_REQUESTED** [review]
Seems you have a failing test around telemetry

**Review by luthfib — APPROVED** [review]

**Comment by WesleyKapow** [comment]
Why not prevent for all localhost? why specifically that port? Does storybook cause reporting? What if we change the port?

**Comment by mrosata** [comment]
> Why not prevent for all localhost? why specifically that port? Does storybook cause reporting? What if we change the port?

Storybook has this request globally mocked out. If we change the port test will fail, also auth won't work anymore b/c currently 3000 is the only allowed localhost port

**Pull request merged**
