### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by luthfib**
Re-organize some code. Recently worked in this folder and realized it was confusing to navigate a lot of where what was.

### CODE REVIEW

**Comment by luthfib** [comment]
Looking into why the tests fail on CI and not locally.

**Comment by luthfib** [comment]
Re-running it fixed it.

**Review by mrosata — APPROVED** [review]
Didn't run locally, but code lgtm

**Review by pmadria3 — APPROVED** [review]
LGTM

**Pull request merged**
