### PR TITLE
CTW-621/Add to Record button on other provider meds

### PR DESCRIPTION
**Pull request by mrosata**
Created an "Add to Record" button in the hamburger menu of `<OtherProviderMedsTable/>`.

Added to storybook (based on conditions mocked cache that @WesleyKapow did) so when someone adds an "other provider" med to their record in storybook, that change is updated in their provider meds table. Note: you will only see this happen when looking at the  `<PatientMedications />` story as the `<OtherProviderMedsTable />` story doesn't show the `<ProviderMedsTable />` and the cache doesn't persist story to story.

### CODE REVIEW

**Review by luthfib — CHANGES_REQUESTED** [review]
Currently this does not work with the autocomplete medications

**Comment by mrosata** [comment]
> Currently this does not work with the autocomplete medications, lmk if you need any help setting that up.

Yeah if you have a quick solution. I just merged main into this branch and it doesn't work with the new autocomplete medication endpoint. It also seems that errors on that autocomplete field never clear. If I do "Add to Record" and submit the medication field is an error (because it's just the text and not selected med), then after selecting a med though, the error state remains (even though the form validates and can submit successfully).
Screen Shot 2022-12-16 at 1 02 27 PM

**Comment by luthfib** [comment]
Seeing this when trying to save. Not sure what we want to do about date asserted. Its locked

image

**Comment by luthfib** [comment]
Maybe don't lock date asserted in add from other medications?

**Comment by mrosata** [comment]
> Maybe don't lock date asserted in add from other medications?

yeah that's a tough one.. if there's no date asserted I suppose just use the current date or fallback to prescribed date? @luthfib @eric-gunther

**Comment by luthfib** [comment]
What if we made the field not locked, that way they practitioner can see the date and change it they field it is necessary. We still fill it in with a default but they have an option of filling it in?

**Comment by luthfib** [comment]
Actually ignore what I said

**Review by luthfib — APPROVED** [review]

**Pull request merged**
