### PR TITLE
Ctw 313 embeddable boost z index value of zus drawer in healthie

### PR DESCRIPTION
**Pull request by melocule**
Deleted image as this repo will be open source (Luthfi)

### CODE REVIEW

**Review by pmadria3 — DISMISSED** [review]
LGTM

**Comment by melocule** [comment]
Thanks for catching this! Added the prefix

**Review by luthfib — CHANGES_REQUESTED** [review]
`ctw-z-[10000]` You are also missing the brackets. Since tailwind doesnt natively have a 10000 value, you have to use the custom modifier which is the brackets

**Review by luthfib — CHANGES_REQUESTED** [review]
Actually I just tested this locally and this does not work. You might want to change your approach and verify that it is working. I would suggest mocking an element that has a higher z-index and ensuring that the drawer still shows up above it. Also make sure you are editing the right div in the drawer component

**Comment by melocule** [comment]
Found the div that z-index is supposed to apply to, tested it against a black box with a z-index set to 9999 (which shows up on top of the drawer when its index is set to 10,001)
image

**Review by luthfib — APPROVED** [review]
LGTM

**Pull request merged**
