### PR TITLE
CTW-381 Automatic Fields Conditions

### PR DESCRIPTION
**Pull request by melocule**
Simplify the user experience of adding a new condition by pre-populating some fields with practical default values. Additionally hides the reported date field, as the now pre-populated value of today's date should not be tampered with by the user.

### CODE REVIEW

**Review by WesleyKapow — CHANGES_REQUESTED** [review]
LGTM, what about updating `recordedDate` when editing a condition OR when adding from "other provider records"? Is that happening?

**Comment by melocule** [comment]
> LGTM, what about updating `recordedDate` when editing a condition OR when adding from "other provider records"? Is that happening?

Hey thanks for bringing this up, I missed that the note at the bottom of the ticket was part of the AC. Changed it to update the recorded date whenever a condition is edited! Also confirmed that the recordedDate is up to date when adding from other provider records.

**Review by luthfib — COMMENTED** [review]
Did you verify that this works? Not sure what dateToISO does to an already dateToISO date, because in `forms/condition.ts` we do `dateToISO(result.data.recordedDate)`. So theoretically we are doing  `dateToISO(dateToISO(new date())`

**Comment by melocule** [comment]
> Did you verify that this works? Not sure what dateToISO does to an already dateToISO date, because in `forms/condition.ts` we do `dateToISO(result.data.recordedDate)`. So theoretically we are doing `dateToISO(dateToISO(new date())`

It works, but it was redundant-- wdy think of this solution? I removed the reportedDate field from the form and just set it to today's date right before sending the request.

**Review by WesleyKapow — APPROVED** [review]
LGTM, love the solution for recordedDate!

**Comment by melocule** [comment]
Thanks Luthfi and Wesley!

**Pull request merged**
