### PR TITLE
CTW-651/encounter details

### PR DESCRIPTION
**Pull request by WesleyKapow**
CTW-651

Screen Shot 2023-01-05 at 3 26 08 PM
Screen Shot 2023-01-05 at 3 26 50 PM

### CODE REVIEW

**Review by luthfib — APPROVED** [review]

**Comment by luthfib** [comment]
Changeset?

**Review by luthfib — COMMENTED** [review]
Why is package-lock.json commited? Did we install anything?

**Comment by WesleyKapow** [comment]
@luthfib Changeset added. And look at package-lock.json changes.. this is a common problem where the auto version PR does not update the lock file with the new version.

**Comment by luthfib** [comment]
Ahh gotcha, it wasnt showing me the diff, so I figured it was a long file of changes.

**Review by luthfib — APPROVED** [review]

**Review by pmadria3 — APPROVED** [review]
LGTM

**Pull request merged**
